config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  root "books#index"

  resources :books do
    collection do
      get 'books/new' #本の登録
      post 'books/create' #登録完了
      get 'books/edit' #本の編集
      post 'books/update' #本の編集完了
      delete 'books/:id', to: 'books#destroy'
      get 'seach'  #本の検索
    end
  end

  resources :information do
    collection do
      get 'users/:id', to: 'information#index' #マイページ
    end
  end
  
  resources :profiles do
    collection do
      get 'profiles/new' #プロフィールの登録
      post 'profiles/create' #登録完了
      get 'profiles/show' #プロフィールの確認
      get 'profiles/edit' #プロフィールの確認
    end
  end

  resources :users, only: [:index,:new, :create, :edit, :update, :destroy]
  resources :books, only: [:new, :create, :show, :delete, :edit, :update]
  resources :information, only: [:show]
  resources :profiles, only: [:new, :create, :show, :edit, :update]
  end

app/controllers/information_controller.rb
class InformationController < ApplicationController

  def show
    user = User.find(params[:id])
    @nickname = current_user.nickname
    @books = current_user.books.page(params[:page]).per(4).order("created_at DESC")
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy if book.user_id == current_user.id
        book.destroy
  end

  def destroyed
  end
  
end

app/helpers/information_helper.rb
module InformationHelper
end

app/views/information/_book.html.haml
- @books.each do |book|
  - if user_signed_in? && current_user.id == book.user_id
    .contents-box{data: {book: {id: book.id}}}
      .content-box
        .content
          .content__text
            %p タイトル
            %h2= book.title
          .content__text__information
            %h2 詳細を見る
            = link_to '編集', "/books/#{book.id}/edit_books_path", method: :get
          .content__text__destroy
            = link_to '削除', "/books/#{book.id}", method: :delete
        

app/views/information/show.html.haml
.data-header-box
  .data-header-box__text
    %p マイページ
    .bookshelf-image
      =image_tag "bookshelf.jpg",size: '400x200',alt:"fmarket"
- if user_signed_in?
  .data-header-box2
    .data-header-box__text2
      %p ユーザーネーム
      .name-text
        = current_user.nickname
#data-box2.data-box2
  .bg
    .data-box2__inner.clearfix
      .data-box2__inner--left.data-box2__header
        .field
          %li.left-box__lists__list
            = link_to "登録内容変更", edit_user_registration_path
          %li.left-box__lists__list
            - if user_signed_in?
              = link_to "プロフィール登録", new_profile_path
          %li.left-box__lists__list
            = link_to "ホームに戻る", root_path, class: 'btn seach'
          
      .data-box2__inner--right.user-form
        = render @books
    .paginate
      = paginate(@books)
                    
        
.data-footer
  .data-footer-box
  