config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  root "books#index"

  resources :books do
    collection do
      get 'books/new' #本の登録
      post 'books/create' #登録完了
      get 'books/edit' #本の編集
      post 'books/update' #本の編集完了
      delete 'books/:id', to: 'books#destroy'
      get 'seach'  #本の検索
    end
  end

  resources :information do
    collection do
      get 'users/:id', to: 'information#index' #マイページ
    end
  end
  
  resources :profiles do
    collection do
      get 'profiles/new' #プロフィールの登録
      post 'profiles/create' #登録完了
      get 'profiles/show' #プロフィールの確認
      get 'profiles/edit' #プロフィールの確認
    end
  end

  resources :users, only: [:index,:new, :create, :edit, :update, :destroy]
  resources :books, only: [:new, :create, :show, :delete, :edit, :update]
  resources :information, only: [:show]
  resources :profiles, only: [:new, :create, :show, :edit, :update]
  end

app/models/book.rb
class Book < ApplicationRecord
  validates :title,  presence: true
  belongs_to :user
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :validates_new, only: :create# 本の登録のバリデーション

  def index
    @books = Book.includes(:user).page(params[:page]).per(4).order("created_at DESC")
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(
      title: book_params[:title], 
      subtitle: book_params[:subtitle], 
      genre: book_params[:genre], 
      author: book_params[:author], 
      the_publisher: book_params[:the_publisher], 
      issue_date: book_params[:issue_date], 
      language: book_params[:language], 
      page_number: book_params[:page_number], 
      visibility: book_params[:visibility], 
      read_day: book_params[:read_day],
      overview: book_params[:overview], 
      impression: book_params[:impression],
      user_id: current_user.id)
      @book.save
  end
end

  def check
    book = Book.find(params[:id])
  end

  def destroy
    if @book.destroy
      redirect_to root_path, notice: '削除しました'
    else
      render :check
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
      @book.update(book_params)
    else
      render :edit
  end

def validates_new
  @book = Book.new(
    title: book_params[:title], 
    user_id: current_user.id)
  render '/books/new' unless @book.valid?
end
  
  private
  def book_params
    params.require(:book).permit(
      :visibility,
      :genre,
      :title, 
      :subtitle, 
      :language,
      :author,
      :the_publisher,
      :issue_date,
      :page_number,
      :overview,
      :read_day,
      :impression,
      )
      .merge(book_id: params[:book_id])
  end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.haml
.contents-box
  .content-box
    .content
      .content__text
        %p タイトル
        %h2= book.title
      .content__text__informations
        .user
          %span 投稿者
        .user-name
          = book.user.nickname
        .data
          %td= link_to '詳細',book_path(book)
        
        
          
          
        

app/views/books/book.html.haml
.book-box1
  .book-box2
    .book
      .book__text
        = book.user.name
        = book.created_at.strftime("%Y年%m月%d日 %H時%M分")
      .book__text
        %p 詳細 

app/views/books/check.html.haml
= form_for(@book) do |f|
  #record-box.record-box
    .bg
      .record-box__inner.clearfix
        .record-box__inner--left.record-box__header
          %h2 登録内容
          
        .record-box__inner--right.user-form
          
          .field
            .field-label
              
            .field-input
              = f.text_field :title, placeholder: 'タイトル(必須)'
          .field
            .field-label
              
            .field-input
              = f.text_field :subtitle, placeholder: 'サブタイトル(なければ空欄)'
          .actions
        
  #record-box2.record-box2
    .bg
      .record-box2__inner.clearfix
        .record-box2__inner--left.record-box2__header
          .field
            %h2 詳細
            .field-label
              %label 
              %span ジャンル
            = f.text_field :genre, placeholder: 'ジャンル(任意)'
            .field-label
              %label 
              %span 著者
            = f.text_field :author, placeholder: '著者(必須)'
            .field-label
              %label 
              %span 出版社
            = f.text_field :the_publisher, placeholder: '出版社(必須)'
            .field-label
              %label 
              %span 発行年月日
            = f.date_field :issue_date, class: 'issue_date'
            .field-label
              %label 
              %span 言語
            = f.text_field :language, placeholder: '言語(任意)'
            .field-label
              %label 
              %span ページ数
            = f.text_field :page_number, placeholder: 'ページ数(任意)'
            .field-label
              %label 
              %span 注目度
            = f.text_field :visibility, placeholder: '注目度(任意)'
            .field-label
              %label 
              %span 読書日
            = f.date_field :read_day, class: 'read_day'
          
        .record-box2__inner--right.user-form
          .field
          
            .field-label
              
            .field-input1
              = f.text_area :overview,class: "statusform",type:"text",placeholder:"概要(任意)",value:""
            .field-label
              
            .field-input2
              = f.text_area :impression,class: "statusform",type:"text",placeholder:"感想(任意)",value:""
          
    .footer
      .action
        = link_to '削除', "/books/#{book.id}", method: :delete
            

app/views/books/complete.html.haml
.complete-screen
  .complete-header-box
  %h1.complete-header-box__icon
  
  .complete
    .complete-box
      .complete-main
        %section.complete-main__header
          %h2 登録完了画面
        .complete-main__box
          .complete-main__form
            = link_to "完了しました", root_path, class: 'btn complete'
  

app/views/books/create.html.haml
.complete-screen
  .complete-header
    .complete-header-box
    %h1.complete-header-box__icon
  
  .complete
    .complete-box
      .complete-main
        %section.complete-main__header
          %h2 登録完了画面
        .complete-main__box
          .complete-main__form
            = link_to "登録完了しました", root_path, class: 'btn complete'
  .footer-complete

app/views/books/destroy.html.haml
.complete-screen
  .complete-header
    .complete-header-box
    %h1.complete-header-box__icon

  .complete-box
    .complete-main
      %section.complete-main__header
        %h2 完了画面
      .complete-main__box
        .complete-main__form
          = link_to "削除しました", root_path, class: 'btn complete'
  .footer-complete

app/views/books/destroyed.html.haml
.complete-screen
  .complete-header
    .complete-header-box
    %h1.complete-header-box__icon

  .complete-box
    .complete-main
      %section.complete-main__header
        %h2 登録完了画面
      .complete-main__box
        .complete-main__form
          = link_to "削除しました", root_path, class: 'btn complete'
  .footer-complete

app/views/books/details.html.haml
= form_for(@books) do |f|
  #record-box.record-box
    .bg
      .record-box__inner.clearfix
        .record-box__inner--left.record-box__header
          %h2 登録内容
          
        .record-box__inner--right.user-form
          
          .field
            .field-label
              
            .field-input
              = f.text_field :title, placeholder: 'タイトル'
          .field
            .field-label
              
            .field-input
              = f.text_field :subtitle, placeholder: 'サブタイトル'
          .actions
        
  #record-box2.record-box2
    .bg
      .record-box2__inner.clearfix
        .record-box2__inner--left.record-box2__header
          .field
            %h2 詳細
            .field-label
              %label 
              %span ジャンル
            = f.text_field :genre, placeholder: 'ジャンル'
            .field-label
              %label 
              %span 著者
            = f.text_field :author, placeholder: '著者'
            .field-label
              %label 
              %span 出版社
            = f.text_field :the_publisher, placeholder: '出版社'
            .field-label
              %label 
              %span 発行年月日
            = f.date_field :issue_date, class: 'issue_date'
            .field-label
              %label 
              %span 言語
            = f.text_field :language, placeholder: '言語'
            .field-label
              %label 
              %span ページ数
            = f.text_field :page_number, placeholder: 'ページ数'
            .field-label
              %label 
              %span 注目度
            = f.text_field :impression, placeholder: '注目度'
            .field-label
              %label 
              %span 読書日
            = f.date_field :read_day, class: 'read_day'
          
        .record-box2__inner--right.user-form
          .field
          
            .field-label
              
            .field-input1
              = f.text_area :overview,class: "statusform",type:"text",placeholder:"概要",value:""
            .field-label
              
            .field-input2
              = f.text_area :impression,class: "statusform",type:"text",placeholder:"感想",value:""
          
    .footer
      .action
        = f.submit "登録する", class: 'btn'
            

app/views/books/edit.html.haml
= form_for(@book) do |f|
  #record-box.record-box
    .bg
      .record-box__inner.clearfix
        .record-box__inner--left.record-box__header
          %h2 登録内容
          
        .record-box__inner--right.user-form
          
          .field
            .field-label
              
            .field-input
              = f.text_field :title, placeholder: 'タイトル'
          .field
            .field-label
              
            .field-input
              = f.text_field :subtitle, placeholder: 'サブタイトル'
          .actions
        
  #record-box2.record-box2
    .bg
      .record-box2__inner.clearfix
        .record-box2__inner--left.record-box2__header
          .field
            %h2 詳細
            .field-label
              %label 
              %span ジャンル
            = f.text_field :genre, placeholder: 'ジャンル'
            .field-label
              %label 
              %span 著者
            = f.text_field :author, placeholder: '著者'
            .field-label
              %label 
              %span 出版社
            = f.text_field :the_publisher, placeholder: '出版社'
            .field-label
              %label 
              %span 発行年月日
            = f.date_field :issue_date, class: 'issue_date'
            .field-label
              %label 
              %span 言語
            = f.text_field :language, placeholder: '言語'
            .field-label
              %label 
              %span ページ数
            = f.text_field :page_number, placeholder: 'ページ数'
            .field-label
              %label 
              %span 注目度
            = f.text_field :visibility, placeholder: '注目度'
            .field-label
              %label 
              %span 読書日
            = f.date_field :read_day, class: 'read_day'
          
        .record-box2__inner--right.user-form
          .field
          
            .field-label
              
            .field-input1
              = f.text_area :overview,class: "statusform",type:"text",placeholder:"概要"
            .field-label
              
            .field-input2
              = f.text_area :impression,class: "statusform",type:"text",placeholder:"感想"
          
    .footer
      .action
        = f.submit "編集する", class: 'btn'
            

app/views/books/home.html.haml
.home-header-box
  .bg
    .header-box
      .header-box__text
        %h2 Read a book
        
      .header-box__text__list
        - if user_signed_in?
          %h2 ログインしています
          = link_to "ログアウト", destroy_user_session_path, method: :delete
          = link_to "本を登録する", record_books_path
        - else
          %h2 ログインしていません
          = link_to "新規登録", new_user_registration_path
          = link_to "ログイン", new_user_session_path
      .books-image
        =image_tag "books.jpg",size: '400x200',alt:"fmarket"

- if user_signed_in?
  .header-box2
    .header-box__text2
      %p ログインしているユーザー
      .home-name-text
        = current_user.nickname
  #home-box2.home-box2
    .bg
      .home-box2__inner.clearfix
        .home-box2__inner--left.home-box2__header
          .field
            %li.left-box__lists__list
              = link_to "プロフィール", profiles_path
            %li.left-box__lists__list
              = link_to "本の検索", seach_books_path
            %li.left-box__lists__list
              %a{:href => "/information/#{current_user.id}"} マイページ
        .home-box2__inner--right.user-form
          = render @books
          
        
- else
  #home-box2.home-box2
    .bg
      .home-box2__inner.clearfix
        .home-box2__inner--left.home-box2__header
          .field
            %li.left-box__lists__list
              = link_to "本の検索", seach_books_path
        .home-box2__inner--right.user-form
          = render @books
  .home-footer
    .footer-box

- if user_signed_in?
  .home-footer
    .footer-box
      
      
          

app/views/books/index.html.haml
.home-header-box
  .bg
    .header-box
      .header-box__text
        %h2 Read a book
        
      .header-box__text__list
        - if user_signed_in?
          %h2 ログインしています
          = link_to "ログアウト", destroy_user_session_path, method: :delete
          = link_to "本を登録する", new_book_path
        - else
          %h2 ログインしていません
          = link_to "新規登録", new_user_registration_path
          = link_to "ログイン", new_user_session_path
      .books-image
        =image_tag "books.jpg",size: '400x200',alt:"fmarket"

- if user_signed_in?
  .header-box2
    .header-box__text2
      %p ログインしているユーザー
      .home-name-text
        = current_user.nickname
  #home-box2.home-box2
    .bg
      .home-box2__inner.clearfix
        .home-box2__inner--left.home-box2__header
          .field
            %li.left-box__lists__list
              = link_to "本の検索", seach_books_path
            %li.left-box__lists__list
              %a{:href => "/information/#{current_user.id}"} マイページ
        .home-box2__inner--right.user-form
          = render @books
      .paginate
        = paginate(@books)
          
        
- else
  #home-box2.home-box2
    .bg
      .home-box2__inner.clearfix
        .home-box2__inner--left.home-box2__header
          .field
            %li.left-box__lists__list
              = link_to "本の検索", seach_books_path
        .home-box2__inner--right.user-form
          = render @books
      .paginate
        = paginate(@books)
  .home-footer
    .footer-box

- if user_signed_in?
  .home-footer
    .footer-box
      
      
          

app/views/books/new.html.haml
= form_for(@book) do |f|
  #record-box.record-box
    .bg
      .record-box__inner.clearfix
        .record-box__inner--left.record-box__header
          %h2 登録内容
          
        .record-box__inner--right.user-form
          
          .field
            .field-label
              
            .field-input
              = f.text_field :title, placeholder: 'タイトル(必須)'
          .field
            .field-label
              
            .field-input
              = f.text_field :subtitle, placeholder: 'サブタイトル(なければ空欄)'
          .actions
            .field-label
              %p タイトルだけでも登録可能
            

        
  #record-box2.record-box2
    .bg
      .record-box2__inner.clearfix
        .record-box2__inner--left.record-box2__header
          .field
            %h2 詳細
            .field-label
              %label 
              %span ジャンル
            = f.text_field :genre, placeholder: 'ジャンル'
            .field-label
              %label 
              %span 著者
            = f.text_field :author, placeholder: '著者'
            .field-label
              %label 
              %span 出版社
            = f.text_field :the_publisher, placeholder: '出版社'
            .field-label
              %label 
              %span 発行年月日
            = f.date_field :issue_date, class: 'issue_date'
            .field-label
              %label 
              %span 言語
            = f.text_field :language, placeholder: '言語'
            .field-label
              %label 
              %span ページ数
            = f.text_field :page_number, placeholder: 'ページ数'
            .field-label
              %label 
              %span 注目度
            = f.text_field :visibility, placeholder: '注目度'
            .field-label
              %label 
              %span 読書日
            = f.date_field :read_day, class: 'read_day'
          
        .record-box2__inner--right.user-form
          .field
          
            .field-label
              
            .field-input1
              = f.text_area :overview,class: "statusform",type:"text",placeholder:"概要",value:""
            .field-label
              
            .field-input2
              = f.text_area :impression,class: "statusform",type:"text",placeholder:"感想",value:""
          
    .footer
      .action
        = f.submit "登録する", class: 'btn'
            

app/views/books/show.html.haml
= form_for(@book) do |f|
  #record-box.record-box
    .bg
      .record-box__inner.clearfix
        .record-box__inner--left.record-box__header
          %h2 タイトル
          
        .record-box__inner--right.user-form
          
          .field
            .field-label
              
            .field-input
              .data
                - if @book.title.present?
                  = @book.title
                - else
                  %p 入力なし
                
          .field
            .field-label
              
            .field-input
              .data
                - if @book.subtitle.present?
                  = @book.subtitle
                - else
                  %p 入力なし
          .actions
        
  #record-box2.record-box2
    .bg
      .record-box2__inner.clearfix
        .record-box2__inner--left.record-box2__header
          .field
            %h2 詳細
            .field-label
              %label 
              %span ジャンル
              .data
                - if @book.genre.present?
                  = @book.genre
                - else
                  %p 入力なし
            .field-label
              %label 
              %span 著者
              .data
                - if @book.author.present?
                  = @book.author
                - else
                  %p 入力なし
            .field-label
              %label 
              %span 出版社
              .data
                - if @book.the_publisher.present?
                  = @book.the_publisher
                - else
                  %p 入力なし
            .field-label
              %label 
              %span 発行年月日
              .data
                - if @book.issue_date.present?
                  = @book.issue_date
                - else
                  %p 入力なし
            .field-label
              %label 
              %span 言語
              .data
                - if @book.language.present?
                  = @book.language
                - else
                  %p 入力なし
            .field-label
              %label 
              %span ページ数
              .data
                - if @book.page_number.present?
                  = @book.page_number
                - else
                  %p 入力なし
            .field-label
              %label 
              %span 注目度
              .data
                - if @book.visibility.present?
                  = @book.visibility
                - else
                  %p 入力なし
            .field-label
              %label 
              %span 読書日
              .data
                - if @book.read_day.present?
                  = @book.read_day
                - else
                  %p 入力なし
          
        .record-box2__inner--right.user-form
          .field
          
            .field-label
              
            .field-input1
              .data
                - if @book.overview.present?
                  = @book.overview
                - else
                  %p 入力なし
            .field-label
              
            .field-input2
              .data
                - if @book.impression.present?
                  = @book.impression
                - else
                  %p 入力なし
          
    .footer
      .action
        = link_to "戻る", root_path, class: 'btn show'
            

app/views/books/update.html.haml
.complete-screen
  .complete-header
    .complete-header-box
    %h1.complete-header-box__icon

  .complete-box
    .complete-main
      %section.complete-main__header
        %h2 登録完了画面
      .complete-main__box
        .complete-main__form
          = link_to "編集しました", root_path, class: 'btn complete'
  .footer-complete